-- AdminRole
REVOKE SELECT, INSERT, UPDATE, DELETE ON CRIME_REPORT FROM AdminRole;
REVOKE SELECT, INSERT, UPDATE, DELETE ON RESPONSE_ACTION FROM AdminRole;
REVOKE SELECT, INSERT, UPDATE, DELETE ON RESIDENT FROM AdminRole;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ADDRESSES FROM AdminRole;
REVOKE SELECT, INSERT, UPDATE, DELETE ON CRIME_CATEGORY FROM AdminRole;
REVOKE SELECT, INSERT, UPDATE, DELETE ON POLICEMAN FROM AdminRole;
REVOKE EXECUTE FROM AdminRole;

-- PolicemanRole
REVOKE SELECT, INSERT, UPDATE ON CRIME_REPORT FROM PolicemanRole;
REVOKE SELECT, INSERT, UPDATE ON RESPONSE_ACTION FROM PolicemanRole;
REVOKE SELECT ON RESIDENT FROM PolicemanRole;
REVOKE SELECT ON ADDRESSES FROM PolicemanRole;
REVOKE SELECT ON CRIME_CATEGORY FROM PolicemanRole;

-- ResidentRole
REVOKE SELECT, INSERT ON CRIME_REPORT FROM ResidentRole;
REVOKE SELECT ON CRIME_CATEGORY FROM ResidentRole;

-- SupervisorRole
REVOKE SELECT, UPDATE ON CRIME_REPORT FROM SupervisorRole;
REVOKE SELECT ON POLICEMAN FROM SupervisorRole;
REVOKE SELECT ON CRIME_CATEGORY FROM SupervisorRole;

-- DataEntryRole
REVOKE INSERT ON CRIME_REPORT FROM DataEntryRole;
REVOKE INSERT ON RESIDENT FROM DataEntryRole;

-- ReadOnlyRole
REVOKE SELECT ON CRIME_REPORT FROM ReadOnlyRole;
REVOKE SELECT ON RESPONSE_ACTION FROM ReadOnlyRole;
REVOKE SELECT ON RESIDENT FROM ReadOnlyRole;
REVOKE SELECT ON POLICEMAN FROM ReadOnlyRole;
REVOKE SELECT ON CRIME_CATEGORY FROM ReadOnlyRole;

-- AnalystRole (Views)
REVOKE SELECT ON vwResidentFullInfo FROM AnalystRole;
REVOKE SELECT ON vwCrimeReportDetails FROM AnalystRole;
REVOKE SELECT ON vwPolicemanAssignments FROM AnalystRole;
REVOKE SELECT ON vwCrimeCategorysummary FROM AnalystRole;
REVOKE SELECT ON vwResponseActionDetails FROM AnalystRole;
REVOKE SELECT ON vwActiveCrimeReports FROM AnalystRole;
REVOKE SELECT ON vwResidentCrimeHistory FROM AnalystRole;
REVOKE SELECT ON vwLatestResponseAction FROM AnalystRole;
REVOKE SELECT ON vwPolicemanSalaryActivity FROM AnalystRole;

GO
