/* Views */

--1.View: RESIDENT_FULL_INFO_VIEW:
CREATE VIEW vwResidentFullInfo AS
SELECT 
    R.RESIDENTSSN,
    R.FIRSTNAME,
    R.MIDDLENAME,
    R.LASTNAME,
    CONCAT(R.FIRSTNAME, ' ', R.MIDDLENAME, ' ', R.LASTNAME) AS FULLNAME,
    R.CONTACTNUMBER,
    R.GENDER,
    R.DATEOFBIRTH,

    /* Address info (may be NULL) */
    (
        SELECT A.CITY
        FROM ADDRESSES A
        WHERE A.RESIDENTSSN = R.RESIDENTSSN
    ) AS CITY,

    (
        SELECT A.STREET
        FROM ADDRESSES A
        WHERE A.RESIDENTSSN = R.RESIDENTSSN
    ) AS STREET,

    (
        SELECT A.APARTMENT
        FROM ADDRESSES A
        WHERE A.RESIDENTSSN = R.RESIDENTSSN
    ) AS APARTMENT

FROM RESIDENT R;
GO

-- 2.View: CRIME_REPORT_DETAILED_VIEW
CREATE VIEW vwCrimeReportDetailes AS
SELECT 
    CR.REPORTID,
    CR.DESCRIPTION,
    CR.STATUS,
    CR.DATETIMEOFWITNESS,
    CR.IMAGECAPTURED,

    -- Resident
    R.RESIDENTSSN,
    CONCAT(R.FIRSTNAME, ' ', R.LASTNAME) AS RESIDENT_FULLNAME,

    -- Policeman
    P.POLICEMANSSN,
    CONCAT(P.FIRSTNAME, ' ', P.LASTNAME) AS POLICEMAN_FULLNAME,

    -- Category
    C.CATEGORYNAME,
    C.DEGREEOFAFFECTION,

    -- Location
    A.CITY,
    A.STREET,
    A.APARTMENT
FROM 
    CRIME_REPORT CR,
    RESIDENT R,
    POLICEMAN P,
    CRIME_CATEGORY C,
    ADDRESSES A
WHERE 
    CR.RESIDENTSSN = R.RESIDENTSSN
    AND CR.POLICEMANSSN = P.POLICEMANSSN
    AND CR.CATEGORYCODE = C.CATEGORYCODE
    AND CR.ID = A.ID;
GO

--3.View: POLICEMAN_ASSIGNMENT_VIEW
CREATE VIEW vwPolicemanAssignments AS
SELECT 
    P.POLICEMANSSN,
    CONCAT(P.FIRSTNAME, ' ', P.LASTNAME) AS POLICEMAN_FULLNAME,
    P.CONTACTNUMBER,
    P.JOININGDATE,
    P.SALARY,

    /* Assigned report info (may be NULL) */
    (
        SELECT CR.REPORTID
        FROM CRIME_REPORT CR
        WHERE CR.POLICEMANSSN = P.POLICEMANSSN
    ) AS REPORTID,

    (
        SELECT CR.STATUS
        FROM CRIME_REPORT CR
        WHERE CR.POLICEMANSSN = P.POLICEMANSSN
    ) AS REPORT_STATUS,

    (
        SELECT CR.DATETIMEOFWITNESS
        FROM CRIME_REPORT CR
        WHERE CR.POLICEMANSSN = P.POLICEMANSSN
    ) AS DATETIMEOFWITNESS

FROM POLICEMAN P;
GO

-- 4.View: CRIME_CATEGORY_SUMMARY_VIEW
CREATE VIEW vwCrimeCategorySummary AS
SELECT 
    C.CATEGORYCODE,
    C.CATEGORYNAME,
    C.DEGREEOFAFFECTION,

    (
        SELECT COUNT(CR.REPORTID)
        FROM CRIME_REPORT CR
        WHERE CR.CATEGORYCODE = C.CATEGORYCODE
    ) AS NUMBER_OF_REPORTS

FROM CRIME_CATEGORY C;
GO

-- 5.View: RESPONSE_ACTION_DETAILS_VIEW
CREATE VIEW vwResponseActionDetails AS
SELECT 
    RA.ACTIONID,
    RA.ACTIONNAME,
    RA.TARGET,
    RA.DATETIMEOFACTION,
    RA.STATUS AS ACTION_STATUS,

    -- Policeman info
    P.POLICEMANSSN,
    CONCAT(P.FIRSTNAME, ' ', P.LASTNAME) AS POLICEMAN_FULLNAME,

    -- Report info
    CR.REPORTID,
    CR.STATUS AS REPORT_STATUS,
    CR.DESCRIPTION
FROM 
    RESPONSE_ACTION RA,
    POLICEMAN P,
    CRIME_REPORT CR
WHERE 
    RA.POLICEMANSSN = P.POLICEMANSSN
    AND RA.REPORTID = CR.REPORTID;
GO

-- 6.View: Active Crime Reports

CREATE VIEW vwActiveCrimeReports AS
SELECT 
    CR.REPORTID,
    CR.DATETIMEOFWITNESS,
    CR.DESCRIPTION,
    CR.STATUS,

    R.RESIDENTSSN,
    R.FIRSTNAME AS RESIDENT_FIRSTNAME,
    R.LASTNAME AS RESIDENT_LASTNAME,

    P.POLICEMANSSN,
    P.FIRSTNAME AS POLICEMAN_FIRSTNAME,
    P.LASTNAME AS POLICEMAN_LASTNAME,

    C.CATEGORYCODE,
    C.CATEGORYNAME,

    A.CITY,
    A.STREET,
    A.APARTMENT
FROM 
    CRIME_REPORT CR,
    RESIDENT R,
    POLICEMAN P,
    CRIME_CATEGORY C,
    ADDRESSES A
WHERE 
    CR.RESIDENTSSN = R.RESIDENTSSN
    AND CR.POLICEMANSSN = P.POLICEMANSSN
    AND CR.CATEGORYCODE = C.CATEGORYCODE
    AND CR.ID = A.ID
    AND CR.STATUS = 'Active';
GO

-- 7.View: Resident Crime History View
CREATE VIEW vwResidentCrimeHistory AS
SELECT
    R.RESIDENTSSN,
    CONCAT(R.FIRSTNAME, ' ', R.LASTNAME) AS RESIDENT_NAME,
    CR.REPORTID,
    CR.DATETIMEOFWITNESS,
    CR.STATUS,
    C.CATEGORYNAME,
    A.CITY,
    A.STREET
FROM 
    RESIDENT R,
    CRIME_REPORT CR,
    CRIME_CATEGORY C,
    ADDRESSES A
WHERE 
    R.RESIDENTSSN = CR.RESIDENTSSN
    AND CR.CATEGORYCODE = C.CATEGORYCODE
    AND CR.ID = A.ID;
GO
-- 8.View: Latest Response Action per Report View

CREATE VIEW vwLatestResponseAction AS
SELECT
    RA.REPORTID,
    MAX(RA.DATETIMEOFACTION) AS LAST_ACTION_DATE
FROM RESPONSE_ACTION RA
GROUP BY
    RA.REPORTID;
GO

-- 9.View: Policeman Salary & Activity Summary View
CREATE VIEW vwPolicemanSalaryActivity AS
SELECT
    P.POLICEMANSSN,
    CONCAT(P.FIRSTNAME, ' ', P.LASTNAME) AS POLICEMAN_NAME,
    P.JOININGDATE,
    P.SALARY,

    (
        SELECT COUNT(RA.ACTIONID)
        FROM RESPONSE_ACTION RA
        WHERE RA.POLICEMANSSN = P.POLICEMANSSN
    ) AS TOTAL_ACTIONS
FROM POLICEMAN P;
GO
